Month 9/step 2
private-lazy-val/react-stellar-burger pull request #18
Opened 2023-11-08 12:28 UTC by private-lazy-val

2023-11-08 14:23 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Сильные стороны работы:
- Есть механизм обновления токена в сокете
- Сокеты открываются и закрываются согласно тех-заданию
- Данные полученные по сокетам хранятся в разных местах хранилища

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:

- Не корректный подсчёт количества ингредиентов в модалке с заказом. Всегда показывает количество равное двум.

<img width="466" alt="image" src="https://github.com/private-lazy-val/react-stellar-burger/assets/60173362/24b9e3a7-c4fb-4729-af92-e5b23b27b325">

- В столбце "В работе" не появляются заказы со статусом pending

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-11-08 14:23 UTC, andryxxa93 commented on src/services/middleware/ws-middleware.js
> +                        socket = new WebSocket(initialWsUrl);
**Можно лучше**
Чтобы новое соединение не инициализировалось слишком часто в случае ошибки - лучше использовать setTimeout

2023-11-09 09:58 UTC, private-lazy-val commented on src/services/middleware/ws-middleware.js
> +                        socket = new WebSocket(initialWsUrl);
1. Поправила
2. Все заказы приходят в статусе "
<img width="440" alt="Screenshot 2023-11-08 at 18 45 28" src="https://github.com/private-lazy-val/react-stellar-burger/assets/56920579/30338ad3-f682-4233-babe-64cac458676d">
done"
3. Добавила таймаут

2023-11-10 05:07 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-11-10 07:19 UTC, merged